title: Before The Fam
author: 8-Bat Media,.
email: hello@batho.ga
description: > # this means to ignore newlines until "baseurl:"
  A 15 Year old Music Producer, DJ, Content Creator and Pro Sleeper/Eater.
  Twitter/Instagram/Snapchat/Facebook: @bathoox

twitter_username: bathoox
github_username:  

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
date_format: "%b %-d, %Y"

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.html

# Build settings
markdown: kramdown
theme: minima
exclude:
  - Gemfile
  - Gemfile.lock
p
